apiVersion: apps/v1
kind: Deployment 
metadata:
  name: cart-page-rs
  namespace: nitin-ns
spec:
  replicas: 3
  selector:
    matchLabels:
     web: cart
  template: #it defines which applications that we have to deploy in cluster 
    metadata:
      labels:
       web: cart
    spec: #it defines behavior of the pod and its coantainer 
      containers:
        - name:  cart-container
          image: muralisocial123/cart-page-test:1.0
          ports: 
            - containerPort: 3000
